# Generated by Django 5.0.3 on 2024-03-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_alter_catalog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='differencePrice',
            field=models.IntegerField(default=10, verbose_name='Скидка в $'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='newPrice',
            field=models.IntegerField(default=10, verbose_name='Конечная цена товара'),
            preserve_default=False,
        ),
    ]
