# Generated by Django 5.0.3 on 2024-03-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_product_differenceprice_product_newprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rayting',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
