# Generated by Django 5.0.3 on 2024-03-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_mainslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadersOfSells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1, verbose_name='states')),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'state',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstApp.leadersofsells', verbose_name='Лидер продаж?'),
            preserve_default=False,
        ),
    ]
