# Generated by Django 5.0.3 on 2024-03-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_leadersofsells_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.leadersofsells', verbose_name='Лидер продаж?'),
        ),
    ]
