# Generated by Django 5.0.3 on 2024-03-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0008_alter_product_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='state',
            new_name='states',
        ),
    ]
