# Generated by Django 5.0.3 on 2024-03-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_rename_state_product_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1, verbose_name='Статус Y или N')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='states',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.leaders', verbose_name='Лидер продаж?'),
        ),
        migrations.DeleteModel(
            name='LeadersOfSells',
        ),
    ]
