# Generated by Django 5.0.3 on 2024-03-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0013_remove_product_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='states',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstApp.leaders'),
            preserve_default=False,
        ),
    ]
