# Generated by Django 5.0.3 on 2024-03-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0014_product_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='states',
        ),
    ]
