# Generated by Django 5.0.3 on 2024-03-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0018_leaders_product_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaders',
            old_name='state',
            new_name='name',
        ),
    ]
