# Generated by Django 5.0.3 on 2024-03-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0019_rename_state_leaders_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='states',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.leaders', verbose_name='Лидер продаж?'),
        ),
    ]
