# Generated by Django 5.0.3 on 2024-03-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0021_alter_product_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='states',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.leaders', verbose_name='Лидер продаж?'),
        ),
    ]
