# Generated by Django 5.0.3 on 2024-04-11 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0025_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30, verbose_name='Предпочитаемый способ доставки')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способ оплаты',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30, verbose_name='Способ доставки')),
                ('price', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cтоимость доставки')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способ доставки',
            },
        ),
        migrations.CreateModel(
            name='BasketOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, null=True, to='firstApp.product')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='http://placehold.it/64x64', null=True, upload_to='avatarsUser/')),
                ('phone', models.IntegerField(max_length=9, verbose_name='Телефон')),
                ('city', models.TextField(blank=True, max_length=20, null=True, verbose_name='Город')),
                ('address', models.TextField(blank=True, max_length=155, null=True, verbose_name='Адрес')),
                ('index', models.IntegerField(blank=True, max_length='9', null=True, verbose_name='Почтовый индекс')),
                ('featuredProducts', models.ManyToManyField(blank=True, null=True, to='firstApp.product', verbose_name='Избранные товары')),
                ('preferredPaymentMethod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.payment', verbose_name='Предпочитаемый способ оплаты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preferredShippingMethod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.shipping', verbose_name='Предпочитаемый способ доставки')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateTimeField(auto_created=True, verbose_name='Дата добавления заказа')),
                ('basketInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.basketofgoods')),
                ('userInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.profile')),
            ],
            options={
                'verbose_name': 'История заказов',
                'verbose_name_plural': 'История заказов',
            },
        ),
        migrations.AddField(
            model_name='basketofgoods',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='firstApp.profile'),
        ),
    ]
