# Generated by Django 5.0.3 on 2024-04-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0026_payment_shipping_basketofgoods_profile_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketofgoods',
            name='users',
        ),
        migrations.AddField(
            model_name='basketofgoods',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.profile'),
        ),
    ]
