# Generated by Django 5.0.3 on 2024-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0027_remove_basketofgoods_users_basketofgoods_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketofgoods',
            name='product',
            field=models.ManyToManyField(to='firstApp.product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='featuredProducts',
            field=models.ManyToManyField(to='firstApp.product', verbose_name='Избранные товары'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='index',
            field=models.IntegerField(blank=True, max_length=9, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
