# Generated by Django 5.0.3 on 2024-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0028_alter_basketofgoods_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
    ]
