# Generated by Django 5.0.3 on 2024-04-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0029_alter_profile_index_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketofgoods',
            name='totalPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая стоимость товаров в корзине'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(max_length=30, verbose_name='Предпочитаемый способ оплаты'),
        ),
    ]
