# Generated by Django 5.0.3 on 2024-04-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0032_alter_featuredproducts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketofgoods',
            name='delivery_Info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.shipping', verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='basketofgoods',
            name='payment_Info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.payment', verbose_name='Оплата'),
        ),
    ]
