# Generated by Django 5.0.3 on 2024-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0033_basketofgoods_delivery_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/avatarsUser/user-defalt.png', null=True, upload_to='avatarsUser/'),
        ),
    ]
