# Generated by Django 5.0.3 on 2024-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0034_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatarsUser/user-defalt.png', null=True, upload_to='avatarsUser/'),
        ),
    ]
