# Generated by Django 5.0.3 on 2024-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0036_remove_profile_index_profile_mail_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/avatarsUser/user-defalt.png', upload_to='avatarsUser/'),
        ),
    ]
