# Generated by Django 5.0.3 on 2024-04-15 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0037_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketofgoods',
            name='product',
        ),
        migrations.AddField(
            model_name='basketofgoods',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.product', verbose_name='Товар'),
        ),
    ]
