# Generated by Django 5.0.3 on 2024-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0038_remove_basketofgoods_product_basketofgoods_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImagesDescr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='productImagesDescr/%Y/%m/%d/', verbose_name='Картинка Товара для описания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='imagesDescr',
            field=models.ManyToManyField(to='firstApp.productimagesdescr', verbose_name='Картинки для карточки товара'),
        ),
    ]
