# Generated by Django 5.0.3 on 2024-05-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0041_rename_post_comment_product'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ от пользователя',
                'verbose_name_plural': 'Заказы от пользователей',
            },
        ),
    ]
