# Generated by Django 5.0.3 on 2024-05-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderuser_created_orderuser_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderuser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='orderuser',
            name='updated',
        ),
    ]
