# Generated by Django 5.0.3 on 2024-05-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderuser_created_orderuser_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
