# Generated by Django 5.0.3 on 2024-05-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0041_rename_post_comment_product'),
        ('orders', '0012_orderuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_user', to='orders.orderuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_user', to='firstApp.product')),
            ],
        ),
    ]
